### ISSUE TITLE
que PCA imprima sqrt( avals(M) ) con 6 decimales (como en los .expected)

### ISSUE THREAD

**Issue by franco-metnum** [MichelleGrenier/facial_recognition_tp2_metodos#1]
a stdout, en la corrida de la cátedra (la de los csv)

y en el archivo .out, en la corrida nuestra (búsqueda de parámetros óptimos)

para después poder tirar `diff -y test1.out test1.expected | less` y comparar con los resultados de la cátedra fácil

ahora imprime los autovalores de la matriz de covarianzas a stdout nomás, creo

**Comment by franco-metnum** [comment]
capaz también preguntar cuánta diferencia es aceptable, entre nuestros autovalores (¿valores singulares?) y los de la cátedra

**Comment by MichelleGrenier** [comment]
Imprime la raiz de los primeros min(15, alfa) avals

**Comment by MichelleGrenier** [comment]
Imprime la raiz de los primeros min(15, alfa) avals
