### ISSUE TITLE
que funcione pca con la corrida busca-parámetros (la del .in y el .out)

### ISSUE THREAD

**Issue by franco-metnum** [MichelleGrenier/facial_recognition_tp2_metodos#14]
ahora creo que segfaultea

está @MichelleGrenier con esto. recién me dijo:
> Contabamos imágenes entrenamiento de la matriz de entrada, pero dsps se dividia en train y test, y no actualizabamos los valores :scream: 

y subió sus cambios y dejó corriendo un experimento que por ahora no segfaulteó

**Comment by MichelleGrenier** [comment]
Ya está andando, corri un par de tests y terminó sin problemas 👌
