### ISSUE TITLE
"Se pide desarrollar una herramienta alternativa que permita trabajar bajo ciertas condiciones con imágenes de tamaño mediano/grande"

### ISSUE THREAD

**Issue by franco-metnum** [MichelleGrenier/facial_recognition_tp2_metodos#15]
dice eso textual el enunciado. no entiendo a qué se refiere. sigue:

> y probar lo siguiente:
> Dada una matriz de covarianza M = X t ∗X, encontrar una relación entre sus autovalores
y sus autovectores con los de la matriz M_alt = X ∗ X t .

será que lo que sea que piden está relacionado con esa demo?

**Comment by franco-metnum** [comment]
ahí me dieron una mano en telegram:

![mediano-grande](https://user-images.githubusercontent.com/37750320/40511697-f01adab4-5f76-11e8-80f2-b4feddc7783a.png)

**Comment by franco-metnum** [comment]
estoy pensando que capaz tiene que ver con un tema de la factorización svd:

suponete que tenés una matriz A de 5 x 20

para hacer la factorización svd podés tomar 2 caminos:

o buscás autovalores y autovectores de A*(A^t), o buscás autovalores y autovectores de (A^t)*A

pero hay una de las dos que va a ser mucho más fácil, porque

A*(A^t) es de 5x5 y (A^t)*A es de 20x20

y creo que el conjunto de autovalores de la más chica, va a estar contenido en el conjunto de autovalores de la más grande

**Comment by MichelleGrenier** [comment]
Pero con desarrollar se refieren  codear? O a dar la idea?

**Comment by franco-metnum** [comment]
mmm capaz la idea es que el programa elija si armar la matriz de covarianza como M=(X^t)\*X o como M_alt = X\*(X^t), según cómo quede más chica?

**Comment by franco-metnum** [comment]
un dato: la matriz de covarianza siempre es simétrica:

M^t = ( (X^t)*X )^t = (X^t)*X = M

M_alt no es M^t, es otra cosa, tiene otra dimensión
