### ISSUE TITLE
que los .out.report tengan formato csv?

### ISSUE THREAD

**Issue by franco-metnum** [MichelleGrenier/facial_recognition_tp2_metodos#16]
vamos a tener un montón de .out.report de todos los experimentos que estamos corriendo

pasar los datos a gráficos a mano es un bajón, lo hice las veces anteriores

lo que hacía era abrir los .out.report con un editor de texto y copiaba los valores a una planilla de cálculo

después usaba las herramientas para graficar del mismo libreoffice calc

capaz si los .out.report fueran valores separados por coma, podríamos concatenarlos, abrirlos con libreoffice calc, seleccionar y graficar más fácil (sin tener que pasar los resultados del reporte a mano)

creo que lo único que importa del .out.result, es lo de abajo de todo, después de \*\*\*RESULTADOS\*\*\*

los datos que salen son: k, alfa, K, método, tiempo, promedio de aciertos, precision y recall

ahora que lo pienso, capaz estaría bueno que salga la cantidad de iteraciones del método de la potencia, también (igual está en el nombre del archivo) (k, alfa, K y el método, también están en el nombre el archivo)

estaría bueno que se pudiera decir con cuántas imágenes se entrenó de cada persona y con cuántas se probó. si K=2, se entrenó con 5 y se probó con 5, esa es fácil. pero si el archivo dice K5, se entrenó con 8 y se probó con 2; en cambio si dice K5inv, se entrenó 2 y se probó con 8 (pero el reporte de ambos dice K=5). con K10 es parecido: se entrenó con 9 y se probó con 1, y K10inv es: entrenó con 1 y probó con 9. habría que buscarle la vuelta para meter la info de si es "inv"(ertido) o no, en el reporte.

también se podría hacer un script o un programa que lleve los .out.report como están ahora, al formato tipo csv que queramos. no se qué será más fácil

si se te ocurre alguna manera mejor de automatizar más los gráficos, es bienvenidísima

**Comment by MichelleGrenier** [comment]
Ahora veo de hacer un programita como el armador, pero q lea las salidas, y las escupa para graficar, con un txt separado por comas.estamos mas q bien, con eso ya podemos usas gnuplot, q ahora me fijo si esta para Windows xD
