### ISSUE TITLE
se rompe si mezclamos imágenes full y reduced? necesitamos manejar ese caso?

### ISSUE THREAD

**Issue by franco-metnum** [MichelleGrenier/facial_recognition_tp2_metodos#7]
me parece que no podemos laburar en ese caso (se rompen las dimensiones de las matrices), pero capaz podemos detectarlo y tirar un error

capaz no hace falta. podemos preguntar

igual está bueno por si le estamos pasando sin querer

**Comment by MichelleGrenier** [comment]
Por cómo está hecho el armador, no se nos pueden mezclar. Y  creo que tiene sentido que no podamos generar una "auto-cara" a partir de imagenes de distintas dimensiones. Yo creo que está bien que no ande en ese caso.
Sí podemos hacer que tire un error si lo detecta. Ahora lo agrego

**Comment by MichelleGrenier** [comment]
Ahi agregué : 
* un error si las imágenes de entrenamiento no tienen el mismo tamaño. 
* un error si las imágenes de prueba no tienen el mismo tamaño. 
* un error si los tamaños de las imágenes de entrenamiento y prueba no coinciden.
